server:
  port: 8080

spring:
  application:
    name: user-api

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    url: jdbc:postgresql://192.168.1.4:5432/dev
    username: postgres
    password: postgres

  flyway:
    schemas: users
  jpa:
    properties:
      hibernate:
        default_schema: users
